version: '3.4'

# this docker configuation is the run flavor (static)

services:
  nginx:
    image: nginx
    container_name: ${DC_PREFIX}-nginx
    volumes:
      - ${BACKEND}/nginx/nginx-run.conf:/etc/nginx/conf.d/default.conf
      - ${BACKEND}/nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf
      - ${FRONTEND}/dist:/usr/share/nginx/html
    networks:
      - default
      - front
    ports:
      - ${PORT}:80
    restart: always

networks:
  default:
    external:
      name: ${DC_NETWORK}
  front:
    driver:
      bridge

