version: '3.4'

# this docker configuation is for dev use only

services:
  nginx-development:
    image: ${APP}-nginx-development
    build:
      context: ${NGINX}
      target: development
      dockerfile: Dockerfile
      args:
        app_name: ${APP}
        app_ver: ${APP_VERSION}
    container_name: ${APP}-nginx-development
    depends_on:
      - frontend-development
    environment:
      - APP
      - ES_PATH
      - ES_INDEX
    volumes:
      - ${APP_PATH}/nginx/nginx-dev.template:/etc/nginx/conf.d/default.template
      - ${APP_PATH}/nginx/tor-ip.conf:/etc/nginx/tor-ip.conf
      - ${APP_PATH}/nginx/aws-ip.conf:/etc/nginx/aws-ip.conf
      - ${APP_PATH}/nginx/nginx.template:/etc/nginx/nginx.template
      - ${FRONTEND}/public:/usr/share/nginx/html
    ports:
      - ${PORT}:80
    restart: always

  frontend-development:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile
      target: development
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_GIT: ${NPM_GIT}
        NPM_VERBOSE: ${NPM_VERBOSE}
    image: ${APP}-frontend-development:${APP_VERSION}
    container_name: ${APP}-frontend-development
    environment:
      - APP
      - PORT
    volumes:
      - ${FRONTEND}/public:/${APP}/public
      - ${FRONTEND}/.eslintrc.js:/${APP}/.eslintrc.js
      - ${FRONTEND}/src:/${APP}/src/
      - ${FRONTEND}/build:/${APP}/build/
      - /${APP}/node_modules
    ports:
      - "${PORT}:${PORT}"

networks:
  default:
    external:
      name: ${DC_NETWORK}
