version: '3.4'

# this docker configuation is for dev use only

services:
  nginx-development:
    image: ${DC_PREFIX}-nginx-development:${APP_VERSION}
    build:
      context: ${NGINX}
      target: development
      dockerfile: Dockerfile
      args:
        app_name: ${APP}
        app_ver: ${APP_VERSION}
    container_name: ${DC_PREFIX}-nginx-development
    depends_on:
      - frontend-development
    environment:
      - APP
      - FRONTEND_DEV_HOST
      - FRONTEND_DEV_PORT
      - ES_PROXY_PATH
      - ES_HOST
      - ES_INDEX
      - ES_PORT
      - API_USER_LIMIT_RATE
      - API_USER_BURST
      - API_USER_SCOPE
      - API_GLOBAL_LIMIT_RATE
      - API_GLOBAL_BURST
    volumes:
      - ${NGINX}/nginx-dev.template:/etc/nginx/conf.d/default.template
      - ${NGINX}/nginx.template:/etc/nginx/nginx.template
      - ${FRONTEND}/public:/usr/share/nginx/html
    ports:
      - ${PORT}:80
    restart: always

  frontend-development:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile
      target: development
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_GIT: ${NPM_GIT}
        NPM_VERBOSE: ${NPM_VERBOSE}
    image: ${DC_PREFIX}-frontend-development:${APP_VERSION}
    container_name: ${DC_PREFIX}-frontend-development
    environment:
      - APP
      - PORT
      - ES_PROXY_PATH
    volumes:
      - ${FRONTEND}/public:/${APP}/public
      - ${FRONTEND}/.eslintrc.js:/${APP}/.eslintrc.js
      - ${FRONTEND}/src:/${APP}/src/
      - ${FRONTEND}/dist-build:/${APP}/build/
      - /${APP}/node_modules

networks:
  default:
    external:
      name: ${DC_NETWORK}
